function [newData] = changeChanNames(colHdr, data, oldMap, newMap)
    % This function is a standalone function that is used along with
    % getSweepDataFlex.m.  getSweepDataFlex.m also returns a map with
    % channel name keys and double values.  This function allows the user
    % to generate a new dataset with user specified double values for the
    % different channel names.
    %
    % oldMap : keys must be strings, values must be doubles (generated by
    %          getSweepDataFlex.m, so it should be correct)
    % newMap : keys must be strings, values must be doubles (generated by
    %          user, must make sure that key and value types are correct)
    % oldToNewMap : maps doubles to doubles
    
    chanIdx = find(strcmp(colHdr, 'iCh'));
    % Make sure chanIdx is one number
    assert(size(chanIdx, 1) == 1);
    assert(size(chanIdx, 2) == 1);
    
    % Create a new map that maps from the old values to the new values so
    % that the old values from the data set given in the argument can be
    % replaced by the new values specified by the user
    oldToNewMap = containers.Map('KeyType', 'double', 'ValueType', 'double');
    oldMapKeys = keys(oldMap);
    newMapKeys = keys(newMap);
    for i = 1:length(oldMapKeys)
        oldVal = oldMap(oldMapKeys{i});
        newVal = newMap(newMapKeys{i});
        oldToNewMap(oldVal) = newVal;
    end
    
    % Replace old channel values with new values specified by the user in
    % the newMap argument
    newData = data;
    numRows = size(newData, 1);
    for i = 1:numRows
        newData(i,chanIdx) = oldToNewMap(newData(i,chanIdx));
    end
end